---
- name: Launch the new EC2 Instance
  community.aws.ec2_instance:
    key_name: "{{ keypair }}"
    instance_type: "{{ instance_type }}"
    image_id: "{{ image }}"
    security_groups: "{{ security_group }}"
    count: "{{ count }}"
    region: "{{ region }}"
    wait: "{{ wait }}"
    subnet_id: "{{ vpc_subnet_id }}"
  register: ec2

- include: add_tags.yml

- include: update_cache.yml